# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0004_auto_20180812_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
    ]
